version: '3.8'

services:
  db:
    container_name: "mathgrass_db"
    image: postgres:latest
    restart: 'no'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/10-init.sql

  adminer:
    container_name: "mathgrass_db_interface"
    image: adminer
    restart: 'no'
    ports:
      - "8081:8080"





